/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ticketingreservationsystem_client;

import java.util.Date;


/**
 *
 * @author Lenovo
 */
public class JPanelSchedule extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSchedule
     * @param airlineName
     */    
    
    public JPanelSchedule(){
        initComponents();    
    }
    
    public JPanelSchedule(String flightNumber,String airlineName, String departureAirport, String arrivalAirport, Date departuteDate, String seatClass, String price) {
        initComponents();
        jLabelFlightNumber.setText(flightNumber);
        jLabelAirlineTrainShipName.setText(airlineName);
        jLabelOriginLocation.setText(departureAirport);
        jLabelDestinationLocation.setText(arrivalAirport);
        jLabelDepartureDate.setText(departuteDate.getDate() + " / " + departuteDate.getMonth() + " / " + departuteDate.getYear());
        jLabelSeatClass.setText(seatClass);
        jLabelPrice.setText(price);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAirlineTrainShipName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOriginLocation = new javax.swing.JLabel();
        jLabelDestinationLocation = new javax.swing.JLabel();
        jLabelDepartureDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelSeatClass = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jButtonBook = new javax.swing.JButton();
        jLabelFlightNumber = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAirlineTrainShipName.setText("Airline,TrainName,ShipName");

        jLabel1.setText("From :");

        jLabel2.setText("To:");

        jLabelOriginLocation.setText("Origin");

        jLabelDestinationLocation.setText("Destination");

        jLabelDepartureDate.setText("Departure Date");

        jLabel7.setText("Seat Class :");

        jLabelSeatClass.setText("seatClass");

        jLabel9.setText("Price :");

        jLabelPrice.setText("jLabel10");

        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });

        jLabelFlightNumber.setText("flightNumber");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAirlineTrainShipName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSeatClass))
                            .addComponent(jLabelFlightNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOriginLocation)
                            .addComponent(jLabelDepartureDate))
                        .addGap(67, 67, 67)
                        .addComponent(jLabelDestinationLocation)
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(jButtonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAirlineTrainShipName)
                    .addComponent(jLabelFlightNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabelSeatClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOriginLocation)
                    .addComponent(jLabelDestinationLocation)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartureDate)
                    .addComponent(jLabelPrice))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        // TODO add your handling code here:
        JFrameBookTicket frameBookTicket = new JFrameBookTicket();
        frameBookTicket.setVisible(true);
        
    }//GEN-LAST:event_jButtonBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAirlineTrainShipName;
    private javax.swing.JLabel jLabelDepartureDate;
    private javax.swing.JLabel jLabelDestinationLocation;
    private javax.swing.JLabel jLabelFlightNumber;
    private javax.swing.JLabel jLabelOriginLocation;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelSeatClass;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
